version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade --user awscli
      - python --version
      - aws --version
      - sam --version
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - sam build --template-file lambda-sam.yaml
      - sam package --template-file .aws-sam/build/template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file lambda-deploy.yaml
artifacts:
  files:
    - lambda-deploy.yaml
  discard-paths: yes